#!/usr/bin/env bash
# mise description="Setup website"

set -euxo pipefail

git_url=""

# Loop through arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --git-url)
            git_url="$2"
            shift 2 # shift twice to bypass key and value
            ;;
        *)
            echo "Unknown parameter passed: $1"
            exit 1
            ;;
    esac
done

if test -n "$git_url"; then
    if test ! -d /var/www/website; then
      git clone $git_url /var/www/website
    fi
    cd /var/www/website
    git pull origin --rebase

  # build quartz
  cd /var/www/website
  npm i --ci
  npx quartz build
fi

