#!/usr/bin/env bash
# mise description="Setup website"

set -euxo pipefail

curl localhost:2019/config/apps/http/servers -H "Content-Type: application/json" -d @${root}/caddy-config.json

git_url=""

# Loop through arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --git-url)
            git_url="$2"
            shift 2 # shift twice to bypass key and value
            ;;
        *)
            echo "Unknown parameter passed: $1"
            exit 1
            ;;
    esac
done


if [[ -n "$git_url" ]]; then
  rm -rf /var/www
  git clone $git_url /var/www
fi
