

[create]
run = """
ssh localhost -p 23231 repo webhooks create {{option(name="repo")}} http://0.0.0.0:9000/hooks/{{option(name="id")}} -e push
"""

[list]
run = """
ssh localhost -p 23231 repo webhooks list {{option(name="repo")}}
"""
