#!/usr/bin/env bash

set -euxo pipefail

# install mise
ssh $SERVER 'curl https://mise.jdx.dev/install.sh | sh'

if [ $(ssh $SERVER "echo \$PATH | grep -c -w \".local/bin\"") -eq 0 ]; then
  ssh $SERVER "echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
fi

# copy global mise config
ssh $SERVER "mkdir -p ~/.config" && (scp config/mise.toml $SERVER:~/.config/mise.toml)

# copy aspects
rsync -av aspects $SERVER:~/
