#!/usr/bin/env bash

set -euxo pipefail

# install mise
if ! [ -x "$(command -v mise)" ]; then
  ssh $SERVER 'curl https://mise.jdx.dev/install.sh | sh'
fi

# add mise to PATH
if [ $(ssh $SERVER "echo \$PATH | grep -c -w \".local/bin\"") -eq 0 ]; then
  ssh $SERVER "echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
fi

# copy global mise config
ssh $SERVER "mkdir -p ~/.config/mise" && (scp config/mise.toml $SERVER:~/.config/mise/config.toml)

# install mise tools
ssh $SERVER "mise install --yes"

# copy aspects
rsync -av aspects $SERVER:~/

# add public key as env
sops exec-env secrets/ssh.yml 'ssh $SERVER "mise set -g PUBLIC_KEY=\"$public_key\""'
