#!/usr/bin/env bash

set -euxo pipefail

# install mise
if ! [ -x "$(command -v mise)" ]; then
  ssh $SERVER 'curl https://mise.jdx.dev/install.sh | sh'
fi

# add mise to PATH
if [ $(ssh $SERVER "echo \$PATH | grep -c -w \".local/bin\"") -eq 0 ]; then
  ssh $SERVER "echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
fi

# copy aspects
rsync -av aspects $SERVER:~/
# add public key as env
sops exec-env secrets/ssh.yml 'ssh $SERVER "echo \"PUBLIC_KEY=$public_key\" >> .env"'
