
[tasks.setup]
description = 'Setup mise'
run = """
#!/usr/bin/env bash
set -euxo pipefail
# copy global mise config
mkdir -p ~/.config/mise
cp -r ${root}/files/mise ~/.config
# copy global mise config
cp ${root}/files/default-npm-packages ~/.default-npm-packages
# install mise tools
mise install --yes
"""
