
[env]
SERVER = "hobl.at"

[tools]
sops = "latest"

[tasks.'setup:local']
description = 'Install'
run = """
#!/usr/bin/env bash
set -euxo pipefail
sops -d --extract '["public_key"]' --output ~/.ssh/id_ed25519_personal-server.pub secrets/ssh.yml
sops -d --extract '["private_key"]' --output ~/.ssh/id_ed25519_personal-server secrets/ssh.yml
chmod 600 ~/.ssh/id_ed25519_personal-server.*
grep -q hobl.at ~/.ssh/config > /dev/null 2>&1 || cat config/ssh_client_config >> ~/.ssh/config
"""

[tasks.print-caddy-config]
description = 'Print caddy config'
run = """
#!/usr/bin/env bash
set -euxo pipefail
ssh $SERVER 'curl http://localhost:2019/config/'
"""

[tasks."setup:repos"]
description = 'Setup repos'
run = """
#!/usr/bin/env bash
set -euxo pipefail
ssh soft repo create memex
ssh soft repo webhooks create memex http://0.0.0.0:9000/hooks/redeploy-website -e push
ssh soft repo create quartz
ssh soft repo webhooks create quartz http://0.0.0.0:9000/hooks/redeploy-website -e push
"""
