#!/usr/bin/env bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

# copy aspects
rsync --quiet -rpt --verbose --compress --chown=:square aspectsV2/ $SERVER:"$SQUARE_PATH/aspects/"

sshcmd="
# symlink aspects to mise tasks
mkdir -p /etc/mise/tasks
find \"$SQUARE_PATH\"/aspects -maxdepth 1 -type f -exec ln -sf {} /etc/mise/tasks \;

echo \"The following mise tasks are available:\" && mise t
"

ssh $SERVER "bash -l -c '$sshcmd'"
