#!/usr/bin/env bash

set -e

#USAGE flag "--repo <repo>" help="Repo name"

mkdir -m 770 -p $SITE_PATH

if test -n "$usage_repo"; then

  repo_path="$SITE_PATH/$usage_repo"

  if ! git -C $x rev-parse --is-inside-work-tree > /dev/null 2>&1; then
      git clone "ssh://localhost:23231/${usage_repo}.git" $repo_path
      # (cd ../webhook && mise r run --name $usage_repo --id redeploy-website)
  fi

  cd $repo_path
  git pull origin --rebase

  npm i --ci
  npx quartz build
fi
